Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "greta"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.11.11"
  config.vm.synced_folder "/laragon/www/la-garenne/vagrant/debian/share", "/home/share"
  config.vm.provision "shell", inline: <<-SHELL
	apt-get update
	apt-get upgrade -y
	apt-get install unzip -y
	apt-get install apache2 -y
	apt-get install mariadb-server -y
	apt-get install git -y
	##### PHP 8.2
	sudo apt update
	sudo apt install lsb-release apt-transport-https ca-certificates software-properties-common -y	
	sudo wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg 
	sudo sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
	sudo apt update
	sudo apt install php8.2
	##### Composer
	php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
	php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
	php composer-setup.php
	php -r "unlink('composer-setup.php');"
	sudo mv composer.phar /usr/local/bin/composer
  SHELL
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
    vb.cpus = 1
	  vb.name = "Debian-Bullseye"
  end
end